### PR TITLE
feat: Agent Pools management + Ability to set on Deployment Settings

### PR DESCRIPTION
**Pull request by MMartyn**
Added new Agent Pool resource to configure customer-managed agent pools. Also modified the Deployment Settings so that those could be configured via provider.

### CODE REVIEW

**Comment by MMartyn** [comment]
Fixes: #227

**Comment by komalali** [comment]
Hey @MMartyn thanks for the contribution here!

**Comment by komalali** [comment]
Test results: https://github.com/pulumi/pulumi-pulumiservice/actions/runs/8513133560

**Review by komalali — COMMENTED** [review]
Looks good except for the feedback about `description` not being required (that will require a regen of the SDKs). Would love to have @glena take a closer look as well.

**Comment by MMartyn** [comment]
Thanks for reviewing. I made the description optional.

**Review by glena — APPROVED** [review]
LGTM!

**Comment by glena** [comment]
Results: https://github.com/pulumi/pulumi-pulumiservice/actions/runs/8538352303/job/23390833759

**Pull request merged**
